### ISSUE TITLE
qispsk@gmail.com on build #25: មិនស្គាល់ or Unrecognized was shown here as I have already…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#56] opened 2016-06-09 07:34 UTC
Feedback from qispsk@gmail.com : មិនស្គាល់ or Unrecognized was shown here as I have already raised in previous build S4.1 build 24

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/be5a865c-1ccd-4d13-8981-f79245ef55cd.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>124 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=57591becccd6250100f9f3cc&bnum=25)

**Comment by ifoche** [comment] 2016-06-15 18:54
Copying here from my email:
We're trying to reproduce this bug without any success. Remember that there are still a bunch of old events in each of the old OUs, so if you selected for example "QIS_test_int" and you're looking at the "Sent" list, then it's normal to see "Unrecognized" in old events. Old data not necessarily is valid, and we cannot guarrantee that the values were properly uploaded. Do you confirm that it's not in the "Sent" list where you're finding the "Unrecognized" issue, or being in the "Sent", that it's happening with values generated by this build (phone features with hash ending by 73d42f5c96dafd5f254867418c9d31bcfb3f548a)?

**Comment by QISPSK** [comment] 2016-06-23 01:46
We've noticed a ton of unrecognized data for QIS test int on the "Sent" tab of the phone application. Oddly, none of this data appears to be in DHIS2, and it was all sent yesterday - a day that we had no training and thus, at least to my knowledge, no one was entering data aimed at the QIS test int OU. 

Any idea why this might be showing up all of a sudden?

**Comment by ifoche** [comment] 2016-06-23 11:55
@QISPSK (also mentioning @josemp10 to include him into this conversation). We can see a lof of blanks listed as day 21 in the server that do not exist app side. Our guess is that all those blanks were submitted by an Android device with the date set to 21 (so it was used 21 for establishing the eventDate), but it happened the 22. So I would say that here there are 2 things:
- These days (21 and 22) there were some configuration and specially sharing settings changes, so our guess is that the explanation for those blanks is that just for yesterday, the events were submitted while the sharing setting was in a staging state where the user KHMCS was not fully allowed for everything, and so blanks events were created. 
- The reason why they appear in the app as day 21, and not day 22, is a bug in how we list the events, sorting them using the completion date and not the event date. 

So our proposal if you agree the previous assessment. What would say if 
- we delete the blanks from the server (probably caused by sharing settings server side), and not treat this problem unless it appears again.
- change the listing sort order to look at the event date

Does it makes sense?

**Comment by QISPSK** [comment] 2016-06-24 02:08
@ifoche Thanks for the detailed response! This does indeed make sense. I think your proposals sound like a good idea and we can keep an eye out for this issue in the future.  We also agree that changing the listing sort order to the event date is preferable to the completion date, although (hopefully) there should only be a minor difference between them.

**Comment by rodmelia** [comment] 2016-06-24 09:50
Sorry for the sharing changes - they occurred as Jose and I were fine tuning them.

**Comment by ifoche** [comment] 2016-06-30 07:29
Can anyone confirm this is done?

**Comment by QISPSK** [comment] 2016-07-11 04:04
@ifoche This issue is also unfortunately not fixed. We're still seeing unrecognized under qis_test_int. It may be associated with switching OUs during the trainings, but we aren't certain. Unrecognized is also likely showing up in the "Blank Data" issue submitted earlier today, but will confirm when we can contact the provider.

**Comment by ifoche** [comment] 2016-07-11 10:12
Hi @QISPSK, I can confirm that this is probably only a consequence of the blank data bug. In fact, this is a protection against that. If this were not showing Unrecognized, the app would be crashing for not finding a valid option. So I would consider this not as a failure itself but as a consequence of blanks...don't you think? (thinking on closing the ticket)

**Comment by QISPSK** [comment] 2016-07-11 10:46
I think closing this ticket is perfectly fine. Definitely seems like the issue is only linked to blank data and should resolve itself once that issue gets fixed.

**Closed as completed** 2016-07-11 11:11 UTC
Labels: question, priority - high, type - content, buddybug
