### ISSUE TITLE
clussiana@psi.org on build #25: Not sure what Unrecognized means. For both surveys, I went…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#63] opened 2016-06-09 10:28 UTC
Feedback from clussiana@psi.org : Not sure what Unrecognized means. For both surveys, I went back to previous questions and changed some answers. Maybe this has something to do with this Unrecognized?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/0279da62-c272-4be3-bf2e-3b696d30f2a8.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575944b032322f010011bcb4&bnum=25)

**Comment by ifoche** [comment] 2016-06-09 11:07
This is definitively a bug. Let me analyse it better

**Comment by ifoche** [comment] 2016-06-15 18:57
Closing it as a duplicate of #56 (Unrecognized bug)

**Closed as completed** 2016-06-15 18:57 UTC
Labels: duplicate, buddybug
