### ISSUE TITLE
Monitor Module and Historical Values

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#99] opened 2016-09-16 08:28 UTC
On both the newest version of the app (1.2.5) and the newest master BB build (43), historical values do not seem to be adding to totals in the monitor module. For example, QIS_test_int has seen 4 cases of Pf this month and 1 case of Pv, however the monitor module only shows 3 cases of Pf and 0 of Pv due to the fact that the two most recent cases were sent after historical values were updated. The same issue is present in the amount of DHA-PIP (and, I assume, AS/MQ) used.

This will likely be a persistent issue until all phones are upgraded to the newest BB version when it's release to the Play Store. In the meantime, can you change the monitor module calculations to include both the new and historical values?

**Comment by ifoche** [comment] 2016-09-16 08:54
Hi @QISPSK. I don't know if I'm properly understanding the issue. Let me tell you my guess.

The app is not automatically refreshing the monitor module when a survey is sent and to do so, you have to manually move to another tab and then back again to monitor. Remember that monitor module is showing only the statistics for the sent surveys (not for those pending to be sent). Hence, once you finish a survey, that will not be automatically in the monitor module, you have to wait for them to disappear from the "pending" list to be sure that it will be in the monitor module. That is the current behaviour.

So the question here is, what behaviour would you expect?
1 - Do you expect the monitoring table to represent also the not yet accepted data?
2 - If that's not the case, do you expect the monitoring table to be automatically refreshed (and so, the dropdown state to be saved in order to set it up again once the module is refreshed)?
3 - Maybe the issue is not 1 or 2 and I didn't get the point. In that case, can you elaborate more on this?

**Comment by josemp10** [comment] 2016-09-16 08:57
@ifoche, this is something we are going to solve from the server side (I
already talked to @QISPSK about that). It is because having the old option
codes values with the new ones in the server

**Comment by ifoche** [comment] 2016-09-16 08:59
Hi @josemp10. Ok, that's fine. Thanks

**Comment by josemp10** [comment] 2016-09-21 11:27
BAO has submitted the script to the server (updates historical option codes values to the current ones).  It runs every 24 hours at 10 am EST.

**Closed as completed** 2016-09-26 10:42 UTC
Labels: bug, priority - medium
