### ISSUE TITLE
clussiana@psi.org on build #26: In the Sent tab, Positive survey: is it possible to change…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#70] opened 2016-06-11 17:37 UTC
Feedback from clussiana@psi.org : In the Sent tab, Positive survey: is it possible to change the denominator at the bottom left corner of the screen from 1 to 9, please?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/98cb5d2d-5ccf-409b-a9b6-95cd9fd4006d.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c4c7446cc3e0100eb9433&bnum=26)

**Comment by ifoche** [comment] 2016-06-11 19:10
Duplicate of #69

**Closed as completed** 2016-06-11 19:10 UTC
Labels: duplicate, invalid, buddybug
