### ISSUE TITLE
clussiana@psi.org on build #25: I took a survey, changed one of the answers I gave (sex),…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#64] opened 2016-06-09 10:33 UTC
Feedback from clussiana@psi.org : I took a survey, changed one of the answers I gave (sex), completed and sent. It's not appearing in the Unsent or Sent tabs. I have now waited for more than 10 minutes.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/bb5b82a2-b5e5-42b3-bdaf-323f6fa18532.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575945e432322f010011bccc&bnum=25)

**Comment by ifoche** [comment] 2016-06-09 11:10
Not able to replicate it...Can you try to follow the same sequence and tell me if you can reproduce that?

**Comment by cristinaelle** [comment] 2016-06-10 07:51
I've redone what I did: took a survey, went back to the sex question, changed my answer from F to M, and then completed and sent the survey. This time it has been correctly sent and I can see the correct answers in the Sent tab. 

I still have those 2 Unrecognized surveys in my Unsent tab, though. If I click on them, I can open them, see the first question, but then I can't swipe to the next question, it's kind of blocked. And I can't either delete them.

**Comment by ifoche** [comment] 2016-06-10 07:55
Looks like a conflict problem...Usually the conflicts happens when the type of the DE is different from the setting in DHIS... As we changed lot of times the server yesterday while we were testing, maybe it's better to wait for this problem to appear again...do you agree?

**Comment by cristinaelle** [comment] 2016-06-10 08:17
Yes.

**Comment by rodmelia** [comment] 2016-06-10 08:21
Crisitna - when you tested this Igancio and I were doing too many server  - let's close this ticket, and if it happens again, then we look at it.

**Closed as completed** 2016-06-10 08:21 UTC
Labels: question, buddybug
