### ISSUE TITLE
qispsk@gmail.com on build #26: Unrecognized has pushed to sent survey page! What does…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#75] opened 2016-06-11 23:02 UTC
Feedback from qispsk@gmail.com : Unrecognized has pushed to sent survey page! What does Unrecognized mean?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/575b4c1dbb15b50100c043ee/0bed0803-f436-4cd6-bd67-6c3fbec2a61e.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>26</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>96% Unplugged</td></tr><tr><td>Memory free</td><td>199 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 26](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575c987653816b010099fa82&bnum=26)

**Comment by QISPSK** [comment] 2016-06-13 01:49
I have been able to replicate "Unrecognized" by simulating intermittent internet connection. If I start a survey with WiFi on, complete a few questions, turn WiFi off, complete a few more, and turn it back on, the survey jumps back to the first question ("RDT"). After completing the survey again, the app registers two "unrecognized" surveys. Is there anyway to ensure that the app doesn't jump back to the first question if the internet goes out?

**Comment by ifoche** [comment] 2016-06-13 06:44
Thanks for this. Effectively it's clearly a bug. Taking care of it.

**Comment by QISPSK** [comment] 2016-06-15 09:29
Unfortunately this issue is still cropping up in version 28. The intermittent internet issue seems to be fixed, but I'm still getting "unrecognized" on the phone (it isn't sending to DHIS2) when I got back and change the answer to branching logic questions.

**Comment by ifoche** [comment] 2016-06-15 13:37
@QISPSK I'm not being able to reproduce it. Can you please write down the sequence you follow to get the error? Just guessing but, can it be a bug when changing the server? I'm just guessing but, did you change your server? Are you pointing to https://www.psi-mis.org? Can you test by cleaning the app and reproducing the bug from zero in order to be 100% sure that without changing from one server to another, pointing to the default server, in a clean install you're able to reproduce it?

**Comment by ifoche** [comment] 2016-06-15 18:56
closing it as a duplicate of #56 (Unrecognize bug)

**Closed as completed** 2016-06-15 18:57 UTC
Labels: duplicate, buddybug
