### ISSUE TITLE
clussiana@psi.org on build #25: The app crashed when I went back to a previous question (in…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#62] opened 2016-06-09 10:24 UTC
Feedback from clussiana@psi.org : The app crashed when I went back to a previous question (in this case Sex) and tried to change the answer (from F to M).

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/079d3382-9cf9-4e09-85c8-efc3a845c4ee.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575943e032322f010011bca5&bnum=25)

**Comment by ifoche** [comment] 2016-06-09 11:04
sorry...can you recheck? I was not able to reproduce it

**Comment by cristinaelle** [comment] 2016-06-10 07:51
Not able to replicate this either. Temporary problem?

**Comment by ifoche** [comment] 2016-06-10 07:53
Maybe an old DB? Not really sure...what do you think? we close the issue and reopen it if it start to happen again and find a pattern?

**Comment by cristinaelle** [comment] 2016-06-10 08:17
Yes.

**Comment by rodmelia** [comment] 2016-06-10 08:22
Let's close it - this happened while Igancio and I were changing the server

**Closed as completed** 2016-06-10 08:22 UTC
Labels: question, buddybug
